[phases.setup]
nixPkgs = ['nodejs-22_x', 'pnpm-9_x']
nixpkgsArchive = '4e6868b1aa3766ab1de169922bb3826143941973'

[phases.install]
cmds = [
  'node --version',
  'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = [
  'pwd',
  'ls -la',
  'ls -la client/',
  'pnpm run build'
]

[start]
cmd = 'pnpm start'

[variables]
VITE_ANALYTICS_ENDPOINT = ''
VITE_ANALYTICS_WEBSITE_ID = ''
VITE_APP_LOGO = ''
VITE_FRONTEND_FORGE_API_KEY = ''
VITE_FRONTEND_FORGE_API_URL = ''
BUILT_IN_FORGE_API_KEY = ''
BUILT_IN_FORGE_API_URL = ''
OAUTH_SERVER_URL = ''
VITE_APP_ID = ''
VITE_OAUTH_PORTAL_URL = ''
